### ISSUE TITLE
Automatically build and publish the (versioned) documentation

### ISSUE THREAD

**Issue by scp93ch** [Spyderisk/system-modeller-docs#1]
When there is a commit to main we should publish the new documentation on the documentation site.

The documentation should be available at `https://spyderisk.org/documentation/modeller/latest/` and at a versioned location `.../modeller/VERSION`.

We therefore also need to be tagging the documentation with a version tag that matches the version tag of the system-modeller.

**Comment by scp93ch** [comment]
Some useful points on security here: https://snyk.io/blog/creating-secure-webhooks/

**Comment by scp93ch** [comment]
Agreed:
* that the docs will be deployed at e.g. `docs.spyderisk.org/system-modeller/<version>`
* we will build and deploy a static site for a tagged release of the docs
  * the CI script will spot the release tag and call a webhook
  * the webhook will check out the release and build the docs
* the release tag will match the release tag used in system-modeller
* when a new docs version is deployed we will link /latest to the version (this will fail if we ever re-release an old version but will do for now)

**Comment by scp93ch** [comment]
@danshearer pointed out by email that it would be more secure just to poll the git repo and build docs if new releases appear. This simplifies things and removes security concerns.

**Comment by danshearer** [comment]
Thanks @scp93ch . Having a VM that does an anonymous ```git pull``` every few minutes for each release tag should give us what we need with almost not scripting involved. The algorithm for walking the release tags should become clear in the Release Process discussion we are having elsewhere. And having documentation for main continually updating without regard to tags is important too.

Using anonymous git polling means that documentation contributors and code contributors are entirely equivalent, all they need is a GitHub login and to edit the MkDocs markdown in the git tree. There should be no GitHub CI and no git hooks. It should be the hosted version of running MkDocs on your local git clone of the documentation. 

Some projects do distinguish between documentation teams/permission and code commit bits, but I feel Spyderisk is a long way from that.

**Comment by scp93ch** [comment]
We can't do a periodic pull for each release tag as the host doing the pulling does not know what they are. The idea would be to do a pull, examine the tags, and then checkout and build each one as a static site deployed in an appropriate path, so that every released version is available.

I don't see how the technical choice of polling vs a CI script and a webhook has anything to do with differentiating between documentation and code contributors.

**Comment by danshearer** [comment]
@scp93ch, after discussion with @panositi I have implemented what you wrote below:
> The idea would be to do a pull, examine the tags, and then checkout and build each one as a static site deployed in an appropriate path, so that every released version is available.

The implementation is in the [scripts directory on this repo](https://github.com/Spyderisk/system-modeller-docs/blob/main/scripts/build-spyderisk-mkdocs.sh). @panositi  has agreed to take this and make the few changes required so that it works in the current production environment, and then push the working script here.

**Comment by danshearer** [comment]
@scp93ch :
> I don't see how the technical choice of polling vs a CI script and a webhook has anything to do with differentiating between documentation and code contributors.

It doesn't. But if we use CI etc then:
1. We are making it so that only people who control the CI process can replicate the docs generation process, for no particular reason
2. We are only detecting part of the relevant changes. Yes, the docs source change on GitHub, and there are new release tags. But also our configuration of mkdocs changes, and also the version of mkdocs.

Therefore I have taken a very simplistic approach. A full git clone is done every time, and a full mkdocs is run for every release tag in that clone. For now that should be robust (I hope?) as we tinker with the documentation toolchain as well as push out Spyderisk releases. If we try to detect changes in all the pieces I think we may trip over ourselves. The extra processing is trivial these days.

**Comment by danshearer** [comment]
I envisage a docs developer (eg me) running this script manually on their laptop to test changes in either the docs or the docs toolchain config.
